openapi: "3.0.0"
info:
  description: ""
  version: "1.0.0"
  title: ""
  termsOfService: ""
  contact:
    email: "info@medical-supplies.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v2"
tags:
- name: "medical-supplies"
  description: "manage medical supplies distribution"
- name: "accounts"
  description: "manage user accounts"
- name: "authentication"
  description: "Access control"
schemes:
- "https"
- "http"
paths:
  /signup:
    post:
      tags:
      - "user"
      summary: "Register new user"
      description: ""
      operationId: "createUser"
      security: 
        - bearerJWT: []
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignUpRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSignUpResponseDTO'
  
components: 
  securitySchemes:
    bearerJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
        
  schemas:
    UserSignUpRequestDTO:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      xml:
        name: "User"
    UserSignUpResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
      xml:
        name: "User"
  